{
 "title": "Crypto streaming dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "coin",
    "query": "SELECT DISTINCT from_currency\nFROM crypto_rate_1min\nORDER BY from_currency"
   }
  ]
 },
 "panels": [
  {
   "title": "Price (1min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  from_currency AS currency,\r\n  rate AS rate,\r\n  window_start AS time\r\nFROM crypto_rate_1min\r\nWHERE $__timeFilter(window_start) AND from_currency = '$coin'\r\nORDER BY from_currency"
    }
   ]
  },
  {
   "title": "Candlebar (5min)",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  from_currency AS currency,\r\n  high_rate   AS High,\r\n  low_rate    AS Low,\r\n  window_start AS time\r\nFROM crypto_rate_5min\r\nWHERE $__timeFilter(window_start) AND from_currency = '$coin'\r\nORDER BY from_currency"
    }
   ]
  },
  {
   "title": "Candlebar (10min)",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  from_currency AS currency,\r\n  high_rate   AS High,\r\n  low_rate    AS Low,\r\n  window_start AS time\r\nFROM crypto_rate_10min\r\nWHERE $__timeFilter(window_start) AND from_currency = '$coin'\r\nORDER BY from_currency"
    }
   ]
  },
  {
   "title": "Line chart of min,max,avg (5min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  from_currency AS currency,\r\n  low_rate AS minimum,\r\n  avg_rate   AS average,\r\n  high_rate AS maximum,\r\n  window_start AS time\r\nFROM crypto_rate_5min\r\nWHERE $__timeFilter(window_start) AND from_currency = '$coin'\r\nORDER BY from_currency"
    }
   ]
  },
  {
   "title": "Line chart min,max,avg (10min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  from_currency AS currency,\r\n  low_rate AS minimum,\r\n  avg_rate   AS average,\r\n  high_rate AS maximum,\r\n  window_start AS time\r\nFROM crypto_rate_10min\r\nWHERE $__timeFilter(window_start) AND from_currency = '$coin'\r\nORDER BY from_currency"
    }
   ]
  }
 ]
}